#!/usr/bin/env ruby
require 'rbconfig'
if RbConfig::CONFIG['host_os'] =~ /mswin|mingw/
        puts "Segmentation fault"
        exit
end

require "pp"
require "yaml"
require "optparse"

@@options = {:config => "~/.cardsrc"}

OptionParser.new do |opts|
  opts.on( '-h', '--help', 'Display this screen' ) do
    puts opts
    exit
  end

  opts.on( '-c', '--config FILE', "Config file" ) do |f|
    @@options[:config] = f 
  end
end.parse!

require "lib/hash.rb"

require "cards_helper.rb"
require "dir_mode.rb"
require "file_mode.rb"
require "fileutils.rb"
require "lib/def.rb"
require "lib/bind.rb"

Dir.glob(File.dirname(__FILE__) + '/commands/*', &method(:require))

user_commands_file = File.expand_path "~/.bu_commands.rb"
require user_commands_file if File.exist? user_commands_file

require "rubygems"
require "backports"
require 'colored'
require "natural_sort_kernel"

require "highline/system_extensions"
include HighLine::SystemExtensions

def main 
        trap("INT") do
                exit
        end
        dir = if have_args? 
                ex_pth ARGV[0]
        else
                ex_pth(rc("default_dir")) 
        end

        goto_dir_mode dir
end

main
